## Compile flags
# mtune and march is an extra optimization flag.
COMMON_FLAGS="-O2 -pipe -march=native -mtune=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

## Locale
LANG="en_US.UTC-8"
LC_MESSAGES="C.UTF-8"

## elog and build logging
# https://wiki.gentoo.org/wiki/Portage_log
# elogs are in ${PORTAGE_LOGDIR}/elog
# build logs (and binpkg) are in ${PORTAGE_LOGDIR}/build
# logs are cleaned after 7 days
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_ELOG_CLASSES="error warn log info"
PORTAGE_ELOG_SYSTEM="echo save"
FEATURES="${FEATURES} clean-logs binpkg-logs split-elog split-log"
# PORTAGE_LOGDIR_CLEAN="find \"\${PORTAGE_LOGDIR}\" -type f ! -name \"summary.log*\" -mtime +14 -delete"

## Use flags
USE="${USE} -X wayland" # Disable X11 and force wayland
USE="${USE} networkmanager bluetooth" # prefer networkmanager over networkd
USE="${USE} -pulseaudio pipewire" # use pipewire over pulseaduio
USE="${USE} bash-completion -elogind pam dbus dist-kernel"

# OBS Capture - https://wiki.gentoo.org/wiki/Niri#OBS
USE="${USE} screencast gstreamer gles2"

# Enables prioritizing a binhost
FEATURES="${FEATURES} getbinpkg"

# Accept license
ACCEPT_LICENSE="@FREE @BINARY-REDISTRIBUTABLE"

# Update with the correct graphics, this conf uses QEMU/KVM type
# https://wiki.gentoo.org/wiki//etc/portage/make.conf#VIDEO_CARDS
# VIDEO_CARDS="amdgpu radeonsi"


# a little confused about this for now
# https://wiki.gentoo.org/wiki/Touchscreen
# https://wiki.gentoo.org/wiki/Wacom
INPUT_DEVICES="wacom libinput"

GRUB_PLATFORMS="efi-64"

# Support your local mirror
# Keep gentoo.org as backup mirror
GENTOO_MIRRORS="https://gentoo.osuosl.org/ http://gentoo.osuosl.org/ http://distfiles.gentoo.org"

## Secure Boot stuff
# Default sbctl key locations
# If lost, disable secure boot in uefi and create news keys. These dont protect data, just data integrity.
USE="${USE} secureboot modules-sign"
MODULES_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
MODULES_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"
SECUREBOOT_SIGN_KEY="/var/lib/sbctl/keys/db/db.key"
SECUREBOOT_SIGN_CERT="/var/lib/sbctl/keys/db/db.pem"
