# mtune is an extra optimization flag, removes most compatiabliity with other archs. Remove if targeting a different arch.
COMMON_FLAGS="-O2 -pipe -march=native -mtune=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LANG="en_US.UTC-8
LC_MESSAGES="C.UTF-8"
# TODO: format to look nicer.
# NOTE: Remove dist-kernel if using custom tuned kernel.
USE="${USE} -pulseaudio -webengine  bash-completion elogind pam libinput dbus pipewire bluetooth wayland gtk qt networkmanager dist-kernel"

# OBS Capture - https://wiki.gentoo.org/wiki/Niri#OBS
USE="${USE} screencast gstreamer gles2"

# Enables prioritizing a binhost
FEATURES="${FEATURES} getbinpkg"

ACCEPT_LICENSE="@FREE @BINARY-REDISTRIBUTABLE"
# Update with the correct graphics, this conf uses QEMU/KVM type
# https://wiki.gentoo.org/wiki//etc/portage/make.conf#VIDEO_CARDS
VIDEO_CARDS="amdgpu radeonsi"

GRUB_PLATFORMS="efi-64"
# Support your local mirror
GENTOO_MIRRORS="https://gentoo.osuosl.org/ http://gentoo.osuosl.org/"