## Compile flags
# mtune and march is an extra optimization flag.
COMMON_FLAGS="-O2 -pipe -march=native -mtune=native"
CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"

## Locale
LANG="en_US.UTC-8"
LC_MESSAGES="C.UTF-8"

## elog and build logging
PORTAGE_LOGDIR="/var/log/portage"
PORTAGE_ELOG_CLASSES="log warn error"
PORTAGE_ELOG_SYSTEM="echo save"
FEATURES="${FEATURES} clean-logs"
# PORTAGE_LOGDIR_CLEAN="find \"\${PORTAGE_LOGDIR}\" -type f ! -name \"summary.log*\" -mtime +14 -delete"

## Use flags
USE="${USE} -X wayland" # Disable X11 and force wayland
USE="${USE} networkmanager bluetooth "
# USE="${USE} -pulseaudio -webengine  pipewire wayland gtk qt networkmanager"
USE="${USE} bash-completion elogind pam dbus dist-kernel"

# OBS Capture - https://wiki.gentoo.org/wiki/Niri#OBS
# USE="${USE} screencast gstreamer gles2"

# Enables prioritizing a binhost
FEATURES="${FEATURES} getbinpkg"

# Accept license
ACCEPT_LICENSE="@FREE @BINARY-REDISTRIBUTABLE"

# Update with the correct graphics, this conf uses QEMU/KVM type
# https://wiki.gentoo.org/wiki//etc/portage/make.conf#VIDEO_CARDS
VIDEO_CARDS="amdgpu radeonsi"

GRUB_PLATFORMS="efi-64"

# Support your local mirror
# GENTOO_MIRRORS="https://gentoo.osuosl.org/ http://gentoo.osuosl.org/"