# This file enables the [GURU repo](https://wiki.gentoo.org/wiki/Project:GURU/Information_for_End_Users)
# a repo that provides more packages maintained by non-gentoo developers.
# emerge --sync guru
[guru]
location = /var/db/repos/guru
sync-type = git
sync-uri = https://github.com/gentoo-mirror/guru.git