#!/usr/bin/env bash
set -ex
cat <<EOF > "/efi/loader/loader.conf"
timeout 12
default $(cat /etc/machine-id)-*
console-mode auto
editor false

auto-entries true
auto-firmware true
auto-reboot true
auto-poweroff true

EOF
