# https://wiki.gentoo.org/wiki/Sccache
# Only configures for rust 
# TODO: Enable configuration for other options
RUSTC_WRAPPER=/usr/bin/sccache
SCCACHE_DIR=/var/cache/sccache
SCCACHE_MAX_FRAME_LENGTH=104857600